name: "Release APK"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish Release APK on Github"
author: "ShoMeThe"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
